spring:
  application:
    name: StudyWise
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://localhost:8081/realms/myrealm

huggingface:
  api:
    url: ${HUGGINGFACE_API_URL}
    key: ${HUGGINGFACE_API_KEY}
generativeia:
  model: ${GENERATIVE_IA_MODEL}
  max-tokens: ${MAX_TOKENS_TO_GENERATE_TEXT}